spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-registry:8848
      config:
        server-addr: nacos-registry:8848
        file-extension: yaml
  config:
    import:
      - nacos:mall-gateway-prod.yaml?refreshEnabled=true
